### PR TITLE
Updated 360 bindings to latest version

### PR DESCRIPTION
**Pull request by tavurth**
I wasn't sure if you'd be interested in this, so feel free to close this PR if you think it's not required.

I simply loaded the game and selected your bindings. The game has updated many bindings recently which is why there seems to be a lot of lines changed.

I then added a few extra keybindings which I find useful, primarily:

**Supercruise**
 - Button to disable orbit lines
 - Button to show the system map
 - Added FSS diagram
 - Added cockpit mode changer

**System**
 - Button to show the system map

**FSS**
 - Added bindings so FSS is usable
 - Added diagram for bindings

**Readme**
 - Use relative positioning of the files to download (Allows for easier git forking)

### CODE REVIEW

**Review by Xarishark — APPROVED** [review]

**Comment by Xarishark** [comment]
This preset project here is Abandoned  you should clone the project and just credit the OP on the notes. I would love to use your changes as I start now and far prefer the xbox controller to a hotas or KB/M

o7 CMDR

**Comment by laurent-indermuehle** [comment]
@tavurth Sorry I missed your pull request. I don't play the game anymore and haven't a 360 controller. Do you fill your work is still relevant to current game state? I so I would merge your pull request.

But last time I check the game, Frontier added a profile that works the same way as this one. So I switch to the one maintained by Frontier :/

**Comment by tavurth** [comment]
Hi @laurent-indermuehle. It's been about 8 months since I played ED, and this one was pretty close to what I was using in game at that time. This supports most of the new functionality such as FSS mode, changing combat exploration mode etc.

In any case it was much closer to the current state of the game than the current state of this original repo (I had to make quite a few changes)

In any case, it seems like having a shareable config on github is nice, and allows people to keep their configs over time without relying on the defaults. If the game now supports a vastly different & preferable config for XBox then perhaps this repo should follow that (with updated PNGs).

**Comment by tavurth** [comment]
Thank you! When I get back into ED I'll make another updated one 🙂

**Pull request merged**
